### ISSUE TITLE
/deep/ combinator is deprecated.

### ISSUE THREAD

**Issue by hwebb** [bendavis78/paper-chip#10]
Awesome component, just a few problems.

You are using /deep/ that is deprecated. https://www.chromestatus.com/features/6750456638341120

Also your CSS import seems deprecated <link rel="import" type="css" href="paper-chip.css"> according to the documentation https://www.polymer-project.org/1.0/docs/devguide/styling.html#external-stylesheets

**Comment by milesje** [comment]
I am seeing this as well.

**Comment by admwx7** [comment]
This element isn't using /deep/ but it is using things like ::slotted that will be removed when it is ported to v1 of the shadow dom spec.
