### ISSUE TITLE
iron-a11y-keys-behavior error.

### ISSUE THREAD

**Issue by milesje** [bendavis78/paper-chip#12]
I receive this exception whenever I use the paper-chip element.

```
iron-a11y-keys-behavior.html:434 Uncaught TypeError: this.keyEventTarget.addEventListener is not a function
(anonymous function) @ iron-a11y-keys-behavior.html:434
_listenKeyEventListeners @ iron-a11y-keys-behavior.html:428
attached @ iron-a11y-keys-behavior.html:325
_invokeBehavior @ polymer-micro.html:434
_doBehavior @ polymer-micro.html:427
(anonymous function) @ polymer-micro.html:211
_makeReady @ polymer-micro.html:109
(anonymous function) @ polymer-micro.html:115
```

**Comment by avizcaino** [comment]
Same problem here. And is making my site work unexpectedly in iOS and Safari. Chrome just ignores the error but on other browsers it stops part of the process.

**Comment by admwx7** [comment]
I know this has been a while, but @milesje or @avizcaino are you still experiencing this issue?  If so I'll plan it into the next milestone.

**Comment by admwx7** [comment]
No response and I can't reproduce
