### ISSUE TITLE
Improve z-index management

### ISSUE THREAD

**Issue by glaucomunsberg** [bendavis78/paper-chip#6]
Hi @bendavis78! So I'm using the paper-chip to long list of persons and it happined:
![screenshot from 2015-10-29 11-13-38](https://cloud.githubusercontent.com/assets/1040010/10819348/a80ac814-7e2e-11e5-939e-a409fc371a14.png) can you recomend something to fix it? I'm now  using this css to chip opened always overlap the chips closed

```
paper-chip[opened]{
          z-index: 9999;
}
```

**Comment by bendavis78** [comment]
Yeah, this could be made easier. I think the fix for this would be to add a higher z-index to the focused/opened states, and also provide CSS mixins to override the z-index when necessary.

I'll look at into adding this soon.

**Comment by admwx7** [comment]
Tested this against master (has v1 shadow-dom updates) and it's working fine, closing this out.
