### ISSUE TITLE
Lable not being displayed

### ISSUE THREAD

**Issue by johnlim** [bendavis78/paper-chip#9]
Hi,
After doing `bower install --save paper-chip` and adding the following element 

```
<paper-chip>
        <div class="icon">P</div>
        <div class="label">Peter Parker</div>
        <div class="caption">pete@dailybugle.com</div>
</paper-chip>
```

 results in 
<img width="62" alt="screen shot 2016-01-21 at 2 36 54 pm" src="https://cloud.githubusercontent.com/assets/2478187/12473350/8275097e-c04c-11e5-845c-c5c606f45ede.png"> instead of 
<img width="134" alt="screen shot 2016-01-21 at 2 37 57 pm" src="https://cloud.githubusercontent.com/assets/2478187/12473361/988517ae-c04c-11e5-9344-f6bbf5c71613.png">
 as shown in the demo. Is there something else I need to add to get it the `Peter Parker` to be displayed?

Also, the demo code and the actual demo at http://bendavis78.github.io/paper-chip/paper-chip/index.html seems to have diverged.

**Comment by johnlim** [comment]
Hi,

I pulled the latest version and the label is actually getting displayed correctly. Any timeline when you'll make a release so that bower will pull the latest? Thanks :)

**Comment by ghost** [comment]
I don't know if you are still working with this component but I think I found how to show the chip as it is shown in the demo:

```
<paper-chip removable>
      <div class="icon">J</div>
      <h1>John</h1>
</paper-chip>
```

![captura de pantalla 2016-05-04 a les 16 54 49](https://cloud.githubusercontent.com/assets/9590299/15018214/f4e96dce-1218-11e6-991e-f4df4ca443de.png)

Seems that the demo [here](https://github.com/bendavis78/paper-chip/blob/master/demo/index.html) is not updated.

If you check [here](http://bendavis78.github.io/paper-chip/paper-chip/index.html), it says:

> h1: The chip label, shown in both closed and opened states

**Comment by johnlim** [comment]
@avizcaino-newuibcn Thanks. Yep, I got it working but was wondering when @bendavis78 would make a release.

**Comment by bennypowers** [comment]
I also have this problem. pulling the latest code from master did not help. neither did adding the removable property.

**Comment by bennypowers** [comment]
My solution was to replace `<content select="foo">` element with `<slot name="foo">` and attendant css selectors as well. usage:

``` html
<paper-chip>
  <div class="label">My Label</div>
  <div class="caption">My Caption</div>
</paper-chip>
```

I've forked and submitted a PR. Until our maintainer resurfaces, you can pull my fork.

**Comment by milesje** [comment]
After updating to version 1.1.2 which was a release that included bennypowers PR I am still unable to get this element to work. All I get is white oval will a dropdown when clicked, and the dropdown will display behind other elements on the page.
![image](https://cloud.githubusercontent.com/assets/537359/22030481/57a74c42-dca3-11e6-8873-815a50cc6182.png)
![image](https://cloud.githubusercontent.com/assets/537359/22030498/677b6306-dca3-11e6-8169-835722fff02e.png)

**Comment by gmltA** [comment]
As I understood, 1.1.2 release is not compatible with current Polymer master branch (which is 1.x).
@milesje to make element work you have to roll paper-chip package back to 1.1.1 or upgrade Polymer itself up to v2.0.

I suggest @bendavis78 to update Polymer dependency to 2.0 for the last release to make it clear for users.

**Comment by milesje** [comment]
OK, I down graded to v1.1.1 and I am still having issues. It does now show my icon in the chip but the label beside it doesn't show. When opened it is still showing behind other components.
![image](https://cloud.githubusercontent.com/assets/537359/23367760/1415413e-fcd1-11e6-8054-55192996d094.png)
![image](https://cloud.githubusercontent.com/assets/537359/23367785/2ff01186-fcd1-11e6-8ba1-9b7500e5de61.png)

```
    <paper-chip label="test">
      <div class="icon">JM</div>
      <h1>Jacob Miles</h1>
      <h2>jacob@netdatacorp.net</h2>
    </paper-chip>
```

**Comment by admwx7** [comment]
Going to close this out, creating appropriate tickets for the migration path: #18 and #19
